### ISSUE TITLE
64 bit build fails - reference to 'uint64_t' is ambiguous

### ISSUE THREAD

**Issue by itoffshore** [jthornber/thin-provisioning-tools#12]
Alpine 2.7.5 - 64 bit with uclibc
GCC 4.8.2
libboost-dev 1.55

64 bit build fails with:

```
    reference to 'uint64_t' is ambiguous
```

Build Log:
http://bld2.alpinelinux.org/buildlogs/build-edge-x86_64.v131211-1497-g9331f94.log

**Comment by LSaldyt** [comment]
Also Gentoo hardened uclibc:
GCC: 8.2.0
libboost: 1.65.0

Fails in the same way.

**Comment by Arusekk** [comment]
Still failing in v8.5 with uClibc on gentoo.

The simpler patch is to replace `uint64_t` with `::uint64_t` (or `boost::uint64_t`, whichever you prefer) in the failing files. It would be better just not to use `using namespace boost`, though, and use `boost::whatever_else` throughout the code, since boost reuses many other global names.

Failing files (only 5):
```
base/application.cc
caching/cache_writeback.cc
thin-provisioning/metadata_dumper.cc
thin-provisioning/thin_dump.cc
thin-provisioning/thin_ls.cc
```
